services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - path: ./env/database.local.env
        required: true
    ports:
      - 4002:5432
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
